### ISSUE TITLE
请问有webSocket的用法么

### ISSUE THREAD

**Issue by 13406169210** [Ai-Thinker-Open/Ai-Thinker-WB2#2]

**Comment by xuhongv** [comment]
你好，这边需要的是 websocket server 吗

**Comment by xuhongv** [comment]
@13406169210 websocket 例程已提供，见 [https://github.com/Ai-Thinker-Open/Ai-Thinker-WB2/tree/main/applications/protocols/mqtt/ws](https://github.com/Ai-Thinker-Open/Ai-Thinker-WB2/tree/main/applications/protocols/mqtt/ws)
