### ISSUE TITLE
MQTT: Client XX disconnected due to protocol error.

### ISSUE THREAD

**Issue by starskyzheng** [Ai-Thinker-Open/Ai-Thinker-WB2#8]
您好，我在使用示例文件applications/protocols/mqtt/tcp出现了报错
我用的mosquitto作为MQTT服务器
BL602开发板只能接受MQTT消息，无法发送消息。
如果使用MQTT发送消息，则会在mosquitto服务器出现“Client XX disconnected due to protocol error.”

不知道是否是MQTT版本问题？

**Comment by starskyzheng** [comment]
抓包看了看，应该是没有正确处理mqtt.msgid的问题，所有的msgid都是0
当qos设置为1或2时候，就没法正确发送了
而默认的qos是1，当然会报错：
 https://github.com/Ai-Thinker-Open/Ai-Thinker-WB2/blob/a370d12a8b268b5e3f7cfe3ef4f32bfe6aad3dd0/applications/protocols/mqtt/tcp/tcp_mqtt_client/tcp_mqtt_client.c#L42

**Comment by xuhongv** [comment]
已修复 @starskyzheng
